// POCs/02_idea_progression_react/src/session/main/session-detail/weight-session/weight-session.tsx
import { PrimitiveAtom, useAtomValue } from 'jotai';
import { focusAtom } from 'jotai/optics';
import { splitAtom } from 'jotai/utils';
import { selectedExerciseAtom } from '../../../shared/session.atoms';
import { ExerciseSetVM, ExerciseVM, SetWeightMetrics } from '../../../shared/session.model';

import '../session-detail.css';
import WeightSet from './weight-set';

const setsAtom = focusAtom(selectedExerciseAtom, (optic) => optic.prop('sets'));
const setsAtomAtoms = splitAtom(setsAtom);

const WeightSession = () => {
    const setAtoms = useAtomValue(setsAtomAtoms) as unknown as PrimitiveAtom<ExerciseSetVM<SetWeightMetrics>>[];
    
    const sets = setAtoms.map((set, index) => 
        <WeightSet key={index} setAtom={set}></WeightSet>
    );

    return (
        <div className="container-fluid">
            <div className="row fw-bold">
                <div className="col"></div>
                <div className="col-3 text-center ps-5 me-3">Target</div>
                <div className="col-3 text-center ps-5 me-3">Actual</div>
                <div className="col-1"></div>
            </div>
            <div className="row fw-bold">
                <div className="col"></div>
                <div className="col-2 text-center p-0">Weight</div>
                <div className="col-1 text-center p-0 me-3">Reps</div>
                <div className="col-2 text-center p-0">Weight</div>
                <div className="col-1 text-center p-0 me-3">Reps</div>
                <div className="col-1 text-center"></div>
            </div>
            {sets}
            {/* <div *ngFor="let exerciseSet of exercise.sets; let i=index" 
                className="row d-flex align-items-center align-self-center"
                [className.selectedRow]="exerciseSet.isEditing"
                (click)="handleStartEditRow($event, exerciseSet)">
                <ng-container *ngIf="!exerciseSet.isEditing">
                    <div className="col fw-bold">{{exerciseSet.setType}}</div>
                    <div className="col-2 text-center p-0">{{exerciseSet.targetMetrics.weight}}</div>
                    <div className="col-1 text-center p-0 me-3">{{exerciseSet.targetMetrics.reps}}</div> 
                    <div className="col-2 text-center p-0">{{exerciseSet.actualMetrics?.weight}}</div>
                    <div className="col-1 text-center p-0 me-3">{{exerciseSet.actualMetrics?.reps}}</div>
                    <div className="col-1 text-center" (click)="handleToggleComplete($event, exerciseSet)">
                        <i className="bi " [ngclassName]="exerciseSet.completed ? 'bi-check-circle' : 'bi-circle'" style="font-size: 1.5rem;"></i>
                    </div>
                </ng-container>
                <ng-container *ngIf="exerciseSet.isEditing">
                    <div className="col d-flex text-center flex-column justify-content-center">
                        <i className="bi bi-arrow-up-circle invisible" style="font-size: 2rem; font-weight: bold;"></i>
                        <select className="form-select" aria-label="Default select example" [(ngModel)]="editRow!.setType">
                            <option *ngFor="let setType of setTypes" [ngValue]="setType.name">{{setType.name}}</option>
                        </select>
                        <i className="bi bi-arrow-down-circle invisible" style="font-size: 2rem; font-weight: bold;"></i>
                    </div>
                    <div className="col-2 d-flex text-center flex-column justify-content-center">
                        <i className="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
                        <div className="input-group">
                            <input type="text" className="form-control text-center" [(ngModel)]="editRow!.targetMetrics.weight">
                            <span className="input-group-text" id="basic-addon2">Kg</span>
                        </div>
                        <i className="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
                    </div>
                    <div className="col-1 d-flex text-center flex-column justify-content-center me-3">
                        <i className="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
                        <div className="input-group">
                            <input type="text" className="form-control text-center reps" [(ngModel)]="editRow!.targetMetrics.reps">
                        </div>
                        <i className="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
                    </div>
                    <div className="col-2 d-flex text-center flex-column justify-content-center">
                        <i className="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
                        <div className="input-group" >
                            <input type="text" className="form-control text-center" [(ngModel)]="editRow!.actualMetrics!.weight">
                            <span className="input-group-text" id="basic-addon2">Kg</span>
                        </div>
                        <i className="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
                    </div>
                    <div className="col-1 d-flex text-center flex-column justify-content-center me-3">
                        <i className="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
                        <div className="input-group">
                            <input type="text" className="form-control text-center reps" [(ngModel)]="editRow!.actualMetrics!.reps">
                        </div>
                        <i className="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
                    </div>
                    <div className="col-1 d-flex flex-column align-items-center align-self-center">
                        <i className="bi bi-trash" (click)="handleDeleteEditRow($event)"></i>
                        <i className="bi bi-x-circle" (click)="handleCancelEditRow($event)"></i>
                        <i className="bi bi-check-circle" (click)="handleConfirmEditRow($event)"></i>
                    </div> 
                </ng-container>
            </div> */}
            <div className="row">
                <div className="col-11"></div>
                <div className="col text-center">
                    <i className="bi bi-plus-circle-fill"></i>
                </div>
            </div>
        </div>
    )
}

export default WeightSession;

// POCs/01_Initial_Ideas_Angular/src/app/session/weight-session/weight-session.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ExerciseSetVM, ExerciseVM, SetWeightMetrics } from '../session.model';

@Component({
    selector: 'app-weight-session',
    templateUrl: './weight-session.component.html',
    styleUrls: ['./weight-session.component.css', '../session.component.css']
})
export class WeightSessionComponent implements OnInit {

    @Input() exercise!: ExerciseVM<SetWeightMetrics>;

    @Output() onToggleComplete: EventEmitter<ExerciseSetVM<SetWeightMetrics>> = new EventEmitter<ExerciseSetVM<SetWeightMetrics>>();
    @Output() onEdit: EventEmitter<ExerciseSetVM<SetWeightMetrics>> = new EventEmitter<ExerciseSetVM<SetWeightMetrics>>();

    constructor() { }

    ngOnInit(): void {

    }

    editRow: ExerciseSetVM<SetWeightMetrics> | null = null;
    handleStartEditRow(exerciseSet: ExerciseSetVM<SetWeightMetrics>, event: Event){
        event.cancelBubble = true;
        this.editRow = Object.assign({}, exerciseSet);
        this.onEdit.emit(exerciseSet);
    }

}

<div class="container-fluid">
    <div class="row fw-bold">
        <div class="col"></div>
        <div class="col-3 text-center ps-5 me-3">Target</div>
        <div class="col-3 text-center ps-5 me-3">Actual</div>
        <div class="col-1"></div>
    </div>
    <div class="row fw-bold">
        <div class="col"></div>
        <div class="col-2 text-center p-0">Weight</div>
        <div class="col-1 text-center p-0 me-3">Reps</div>
        <div class="col-2 text-center p-0">Weight</div>
        <div class="col-1 text-center p-0 me-3">Reps</div>
        <div class="col-1 text-center"></div>
    </div>
    <div *ngFor="let exerciseSet of exercise.sets" 
        class="row d-flex align-items-center align-self-center"
        [class.selectedRow]="exerciseSet.isEditing"
        (click)="handleStartEditRow(exerciseSet, $event)">
        <div class="col fw-bold">{{exerciseSet.name}}</div>
        <div class="col-2 text-center p-0">{{exerciseSet.targetMetrics.weight}}</div>
        <div class="col-1 text-center p-0 me-3">{{exerciseSet.targetMetrics.reps}}</div>
        <div class="col-2 text-center p-0">{{exerciseSet.actualMetrics.weight}}</div>
        <div class="col-1 text-center p-0 me-3">{{exerciseSet.actualMetrics.reps}}</div>
        <div class="col-1 text-center" (click)="onToggleComplete.emit(exerciseSet)"><i class="bi " [ngClass]="exerciseSet.completed ? 'bi-check-circle' : 'bi-circle'" style="font-size: 1.5rem;"></i></div>
    </div>


    <!-- <div *ngIf="editRow" class="row selectedRow">
        <div class="col d-flex text-center flex-column justify-content-center">
            <i class="bi bi-arrow-up-circle invisible" style="font-size: 2rem; font-weight: bold;"></i>
            <select class="form-select" aria-label="Default select example">
                <option selected>Set</option>
                <option value="1">Warm-up</option>
                <option value="2">Drop set</option>
                <option value="3">Failure</option>
              </select>
            <i class="bi bi-arrow-down-circle invisible" style="font-size: 2rem; font-weight: bold;"></i>
        </div>
        <div class="col-2 d-flex text-center flex-column justify-content-center">
            <i class="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
            <div class="input-group">
                <input type="text" class="form-control text-center" value="55">
                <span class="input-group-text" id="basic-addon2">Kg</span>
            </div>
            <i class="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
        </div>
        <div class="col-1 d-flex text-center flex-column justify-content-center me-3">
            <i class="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
            <div class="input-group">
                <input type="text" class="form-control text-center reps" value="8">
            </div>
            <i class="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
        </div>
        <div class="col-2 d-flex text-center flex-column justify-content-center">
            <i class="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
            <div class="input-group" >
                <input type="text" class="form-control text-center" value="55">
                <span class="input-group-text" id="basic-addon2">Kg</span>
            </div>
            <i class="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
        </div>
        <div class="col-1 d-flex text-center flex-column justify-content-center me-3">
            <i class="bi bi-arrow-up-circle" style="font-size: 2rem; font-weight: bold;"></i>
            <div class="input-group">
                <input type="text" class="form-control text-center reps" value="9">
            </div>
            <i class="bi bi-arrow-down-circle" style="font-size: 2rem; font-weight: bold;"></i>
        </div>
        <div class="col-1 d-flex flex-column align-items-center align-self-center">
            <i class="bi bi-trash"></i>
            <i class="bi bi-x-circle"></i>
            <i class="bi bi-check-circle" (click)="handleConfirmEdit()"></i>
        </div> 
    </div>-->
</div>
